worker_processes 3;

error_log logs/error.log error;

events {
    worker_connections 1024;
    multi_accept on;
}

http {
    lua_shared_dict producer_locks 5m;

    include mime.types;
    default_type application/octet-stream;

    lua_package_path "KAFKA_LIB_PATH;LAB_LIB_PATH;/usr/local/openresty/lualib/?.lua;;";

    init_by_lua_file OPENRESTY_DIR/luaconfigs/init.lua;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name localhost;

        location / {
            root html;
            index index.html index.htm;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root html;
        }
    }

    include OPENRESTY_DIR/nginx/conf/conf.d/*.conf;
}
