worker_processes 3;

error_log logs/error.log error;

events {
    worker_connections 1024;
    multi_accept on;
}

http {
    lua_shared_dict producer_locks 5m;

    include mime.types;
    default_type application/octet-stream;

    lua_package_path "LUA_PACKAGE_PATH";

    init_by_lua_file /usr/local/openresty/luaconfigs/init.lua;

    sendfile on;
    keepalive_timeout 65;

    include /usr/local/openresty/nginx/conf/conf.d/*.conf;
}

