server {
    listen 80;
    server_name DOMAIN_NAME;

    client_max_body_size 10m;
    client_body_buffer_size 1m;

    location /kafka/sync {
        content_by_lua_file /usr/local/openresty/luaconfigs/producer_sync.lua;
    }

    location /kafka/async {
        content_by_lua_file /usr/local/openresty/luaconfigs/producer_async.lua;
    }

    location = /basic_status {
        stub_status;
    }
}

